### ISSUE TITLE
db seeds wants to run more than once

### ISSUE THREAD

**Issue by OttoVonBismark** [OttoVonBismark/boggygofast#2]
Not really sure what's going on here, but db:seed seems to want to run twice when invoked once, as indicated by the output here:

> raegaltboggart@Catoblepas /mnt/b/Dev_Stuff/RoR/boggygofast (master) $ rails db:reset && rails db:seed
Dropped database 'db/development.sqlite3'
Dropped database 'db/test.sqlite3'
Created database 'db/development.sqlite3'
Created database 'db/test.sqlite3'
-- create_table("games", {:force=>:cascade})
   -> 0.4134s
-- create_table("runcats", {:force=>:cascade})
   -> 0.0895s
-- create_table("speedruns", {:force=>:cascade})
   -> 0.1400s
-- create_table("users", {:force=>:cascade})
   -> 0.0628s
-- create_table("games", {:force=>:cascade})
   -> 0.3468s
-- create_table("runcats", {:force=>:cascade})
   -> 0.0783s
-- create_table("speedruns", {:force=>:cascade})
   -> 0.1689s
-- create_table("users", {:force=>:cascade})
   -> 0.0900s
rails aborted!
ActiveRecord::RecordInvalid: Validation failed: Email has already been taken
/home/raegaltboggart/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.2/lib/active_record/validations.rb:78:in `raise_validation_error'
/home/raegaltboggart/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.2/lib/active_record/validations.rb:50:in `save!'
/home/raegaltboggart/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.2/lib/active_record/attribute_methods/dirty.rb:43:in `save!'
/home/raegaltboggart/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.2/lib/active_record/transactions.rb:313:in `block in save!'
/home/raegaltboggart/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.2/lib/active_record/transactions.rb:384:in `block in with_transaction_returning_status'
/home/raegaltboggart/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.2/lib/active_record/connection_adapters/abstract/database_statements.rb:225:in `block in transaction'
/home/raegaltboggart/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.2/lib/active_record/connection_adapters/abstract/transaction.rb:194:in `block in within_new_transaction'
/home/raegaltboggart/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.2/lib/active_record/connection_adapters/abstract/transaction.rb:191:in `within_new_transaction'
/home/raegaltboggart/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.2/lib/active_record/connection_adapters/abstract/database_statements.rb:225:in `transaction'
/home/raegaltboggart/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.2/lib/active_record/transactions.rb:210:in `transaction'
/home/raegaltboggart/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.2/lib/active_record/transactions.rb:381:in `with_transaction_returning_status'
/home/raegaltboggart/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.2/lib/active_record/transactions.rb:313:in `save!'
/home/raegaltboggart/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.2/lib/active_record/suppressor.rb:46:in `save!'
/home/raegaltboggart/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.2/lib/active_record/persistence.rb:51:in `create!'
/mnt/b/Dev_Stuff/RoR/boggygofast/db/seeds.rb:2:in `<top (required)>'
/home/raegaltboggart/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:286:in `load'
/home/raegaltboggart/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:286:in `block in load'
/home/raegaltboggart/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:258:in `load_dependency'
/home/raegaltboggart/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:286:in `load'
/home/raegaltboggart/.rvm/gems/ruby-2.4.1/gems/railties-5.1.2/lib/rails/engine.rb:549:in `load_seed'
/home/raegaltboggart/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.2/lib/active_record/tasks/database_tasks.rb:270:in `load_seed'
/home/raegaltboggart/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.2/lib/active_record/railties/databases.rake:184:in `block (2 levels) in <top (required)>'
/home/raegaltboggart/.rvm/gems/ruby-2.4.1/gems/railties-5.1.2/lib/rails/commands/rake/rake_command.rb:21:in `block in perform'
/home/raegaltboggart/.rvm/gems/ruby-2.4.1/gems/railties-5.1.2/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/home/raegaltboggart/.rvm/gems/ruby-2.4.1/gems/railties-5.1.2/lib/rails/command.rb:46:in `invoke'
/home/raegaltboggart/.rvm/gems/ruby-2.4.1/gems/railties-5.1.2/lib/rails/commands.rb:16:in `<top (required)>'
/mnt/b/Dev_Stuff/RoR/boggygofast/bin/rails:9:in `require'
/mnt/b/Dev_Stuff/RoR/boggygofast/bin/rails:9:in `<top (required)>'
/home/raegaltboggart/.rvm/gems/ruby-2.4.1/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `load'
/home/raegaltboggart/.rvm/gems/ruby-2.4.1/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `call'
/home/raegaltboggart/.rvm/gems/ruby-2.4.1/gems/spring-2.0.2/lib/spring/client/command.rb:7:in `call'
/home/raegaltboggart/.rvm/gems/ruby-2.4.1/gems/spring-2.0.2/lib/spring/client.rb:30:in `run'
/home/raegaltboggart/.rvm/gems/ruby-2.4.1/gems/spring-2.0.2/bin/spring:49:in `<top (required)>'
/home/raegaltboggart/.rvm/gems/ruby-2.4.1/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `load'
/home/raegaltboggart/.rvm/gems/ruby-2.4.1/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `<top (required)>'
/mnt/b/Dev_Stuff/RoR/boggygofast/bin/spring:15:in `require'
/mnt/b/Dev_Stuff/RoR/boggygofast/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
Tasks: TOP => db:seed
(See full trace by running task with --trace)

This shouldn't be possible, since the line that raises the exception is only ran once and is not part of any loop.

```Ruby
User.create!(name: "Example User", email: "adminman@boggygofast.org", password: "foobar", password_confirmation: "foobar", admin: true)
```
Despite the error, the database gets structured correctly before the exception gets raised, so I'm considering this low-priority. That said, if anyone wants to tackle this, the file in question is `db/seeds.rb` so feel free to have at it.

**Comment by OttoVonBismark** [comment]
As it turns out, I was a doofus all this time and didn't realize that db:reset automatically runs the seed at the end of it's process. I discovered this by trying to wrap the contents of the seed in a '1.time do' block (got a NoMethodError for "time" in seeds.rb)

Since that effectively nullifies this as an issue, I'll close it here.
